"""Adding the Chatting Message  Model

Revision ID: 0cd72bfb8d35
Revises: b3c0562df721
Create Date: 2025-12-09 15:05:51.092917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd72bfb8d35'
down_revision: Union[str, Sequence[str], None] = 'b3c0562df721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
