"""describe change

Revision ID: d197e0b2fe67
Revises: 4f71e64dbb81
Create Date: 2025-12-08 14:07:32.431623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd197e0b2fe67'
down_revision: Union[str, Sequence[str], None] = '4f71e64dbb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_files', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('upload_files', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_files', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('upload_files', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
